{
    'name':'Event management',
    'version':'1.0',
    'category':'Events',
    'license': 'LGPL-3',
    'author':'Moksha Shah',
    'depends':['base','mail','website'],
    'data':[
        'data/attendee_registration_template.xml',
        'data/event_management_homepage.xml',
        'data/ir_sequence_data.xml',
        'data/attendee_email_template.xml',
        'data/attendee_scheduled_actions.xml',
        'security/ir.model.access.csv',
        'security/event_security.xml',
        'views/actions.xml',
        'views/menu.xml',
        'reports/attendee_report.xml',
        'reports/attendee_report_template.xml',
         # 'views/event_dashboard_template.xml',
        'views/dashboard_template.xml',
        'views/events.xml',
        'views/event_category.xml',
        'views/event_attendee.xml',
        'views/tickets.xml',
        'views/ticket_type.xml',
        'views/sponsor.xml',
        'views/speaker.xml',
        # 'views/payment_success_page.xml',
        # 'views/razorpay_payment_page.xml',
        'views/venue.xml',
    ],
   'assets':{
        'web.assets_backend':[
            # 'Event_management/static/src/js/dashboard.js',
        ],
    }
    }
